services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins-openbmc
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/var/jenkins_home/workspace/openbmc-tests
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins-net

  qemu-openbmc:
    # СОБИРАЕМ ОБРАЗ ЛОКАЛЬНО ИЗ DOCKERFILE
    build: .
    container_name: qemu-openbmc
    privileged: true
    ports:
      - "2443:2443"
      - "2222:2222"
    networks:
      - jenkins-net
    # Healthcheck здесь не нужен, так как сборка гарантирует наличие всего необходимого

volumes:
  jenkins_data:

networks:
  jenkins-net:
    driver: bridge